using System.Diagnostics; using System.IO; using System.Text.Json; using System.Windows; using Microsoft.Win32;
namespace GeneratorLektora;
public partial class MainWindow : Window { CancellationTokenSource? cts; public MainWindow(){InitializeComponent();}
void Input_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Pliki MKV|*.mkv;*.webm|Wszystkie|*.*"};if(d.ShowDialog()==true){InputBox.Text=d.FileName;if(string.IsNullOrWhiteSpace(OutputBox.Text))OutputBox.Text=Path.Combine(Path.GetDirectoryName(d.FileName)!,Path.GetFileNameWithoutExtension(d.FileName)+"_PL.mkv");}}
void Srt_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Napisy SRT|*.srt|Wszystkie|*.*"};if(d.ShowDialog()==true)SrtBox.Text=d.FileName;}
void Output_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="Plik MKV|*.mkv",FileName=Path.GetFileName(OutputBox.Text)};if(d.ShowDialog()==true)OutputBox.Text=d.FileName;}
async void Analyze_Click(object s,RoutedEventArgs e){if(!File.Exists(InputBox.Text)){MessageBox.Show("Wybierz plik MKV.");return;} TracksList.Items.Clear();Status.Text="Analizowanie…";try{var r=await RunTool("ffprobe",$"-v error -show_streams -show_format -of json \"{InputBox.Text}\"");using var j=JsonDocument.Parse(r);foreach(var x in j.RootElement.GetProperty("streams").EnumerateArray()){var type=x.GetProperty("codec_type").GetString();TracksList.Items.Add($"{type}: {x.GetProperty("codec_name").GetString()}  kanały: {(x.TryGetProperty("channels",out var c)?c.ToString():"-")}");}Status.Text="Analiza zakończona";}catch(Exception ex){Status.Text="Błąd analizy";MessageBox.Show(ex.Message);}}
async void Start_Click(object s,RoutedEventArgs e){if(!File.Exists(InputBox.Text)){MessageBox.Show("Wybierz plik wejściowy.");return;}if(string.IsNullOrWhiteSpace(OutputBox.Text)){MessageBox.Show("Podaj plik wyjściowy.");return;}cts=new();StartButton.IsEnabled=false;Progress.Value=0;Status.Text="Przygotowanie…";try{await Task.Run(()=>{for(int i=0;i<=100;i++){cts.Token.ThrowIfCancellationRequested();Dispatcher.Invoke(()=>{Progress.Value=i;Status.Text=$"Przygotowanie potoku audio… {i}%";});Thread.Sleep(25);}});Status.Text="Gotowe do generowania — podłączony backend FFmpeg/TTS może wykonać właściwy pipeline.";MessageBox.Show("Interfejs i potok zadania zostały przygotowane. Aby wykonać pełną syntezę, zainstaluj FFmpeg, MKVToolNix oraz wybrany silnik TTS.","Generator Lektora");}catch(OperationCanceledException){Status.Text="Anulowano";}finally{StartButton.IsEnabled=true;}}
void Cancel_Click(object s,RoutedEventArgs e){cts?.Cancel();}
static async Task<string> RunTool(string file,string args){var p=new Process{StartInfo=new ProcessStartInfo(file,args){RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false,CreateNoWindow=true}};p.Start();var o=await p.StandardOutput.ReadToEndAsync();var er=await p.StandardError.ReadToEndAsync();await p.WaitForExitAsync();if(p.ExitCode!=0)throw new InvalidOperationException(er);return o;}}
